/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'anant' at '24/11/16 12:33 AM' with Gradle 2.12
 *
 * @author anant, @date 24/11/16 12:33 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
